"""initial schema

Revision ID: 4d6b21a86ea9
Revises: 
Create Date: 2026-09-04 00:26:51.169447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate renders the JSONB variant in shared/models.py as
# `postgresql.JSONB(astext_type=Text())` and does not import Text itself.
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4d6b21a86ea9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_attempts_email'), ['email'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('creator_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('handle', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('niche', sa.String(length=200), nullable=False),
    sa.Column('pain', sa.Text(), nullable=False),
    sa.Column('platforms', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('followers', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('median_views', sa.Integer(), nullable=True),
    sa.Column('cadence_goal', sa.Integer(), nullable=False),
    sa.Column('filming_days', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('budget_sgd_per_week', sa.Integer(), nullable=True),
    sa.Column('voice', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('goals', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('no_go', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('brand_targets', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('best_performing', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('worst_performing', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'handle', name='uq_profile_user_handle')
    )
    with op.batch_alter_table('creator_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('analytics_posts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=160), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('avg_watch_pct', sa.Float(), nullable=True),
    sa.Column('median_ratio', sa.Float(), nullable=True),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['creator_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_posts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_posts_profile_id'), ['profile_id'], unique=False)

    op.create_table('artifacts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('opportunity_id', sa.String(length=160), nullable=True),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['creator_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifacts_profile_id'), ['profile_id'], unique=False)
        batch_op.create_index('ix_artifacts_profile_opp', ['profile_id', 'opportunity_id'], unique=False)

    op.create_table('calendar_events',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.String(length=240), nullable=False),
    sa.Column('opportunity_id', sa.String(length=160), nullable=True),
    sa.Column('slot', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['creator_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'id')
    )
    op.create_table('engagement_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('classification', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('opportunity_id', sa.String(length=160), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['creator_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('engagement_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_engagement_items_profile_id'), ['profile_id'], unique=False)

    op.create_table('memory',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('wins', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('losses', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('next_bias', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['creator_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('opportunities',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.String(length=160), nullable=False),
    sa.Column('record', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('qualification', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['creator_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id', 'id')
    )
    op.create_table('rag_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.String(length=60), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['creator_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rag_documents_profile_id'), ['profile_id'], unique=False)

    op.create_table('runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['creator_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_runs_profile_id'), ['profile_id'], unique=False)

    op.create_table('agui_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agui_events', schema=None) as batch_op:
        batch_op.create_index('ix_agui_events_run_seq', ['run_id', 'seq'], unique=False)

    op.create_table('run_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('agent', sa.String(length=120), nullable=False),
    sa.Column('pattern', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('artifact_ref', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.create_index('ix_run_events_run_seq', ['run_id', 'seq'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('run_events', schema=None) as batch_op:
        batch_op.drop_index('ix_run_events_run_seq')

    op.drop_table('run_events')
    with op.batch_alter_table('agui_events', schema=None) as batch_op:
        batch_op.drop_index('ix_agui_events_run_seq')

    op.drop_table('agui_events')
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_runs_profile_id'))

    op.drop_table('runs')
    with op.batch_alter_table('rag_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rag_documents_profile_id'))

    op.drop_table('rag_documents')
    op.drop_table('opportunities')
    op.drop_table('memory')
    with op.batch_alter_table('engagement_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_engagement_items_profile_id'))

    op.drop_table('engagement_items')
    op.drop_table('calendar_events')
    with op.batch_alter_table('artifacts', schema=None) as batch_op:
        batch_op.drop_index('ix_artifacts_profile_opp')
        batch_op.drop_index(batch_op.f('ix_artifacts_profile_id'))

    op.drop_table('artifacts')
    with op.batch_alter_table('analytics_posts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_posts_profile_id'))

    op.drop_table('analytics_posts')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))

    op.drop_table('sessions')
    with op.batch_alter_table('creator_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_profiles_user_id'))

    op.drop_table('creator_profiles')
    op.drop_table('users')
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_attempts_email'))

    op.drop_table('login_attempts')
    # ### end Alembic commands ###
